### ISSUE TITLE
Documentation checklist

### ISSUE THREAD

**Issue by galudino** [galudino/gcs_graph#1]
This checklist will expand as more headers/sources are added to the repository.
Remember that each file should have:
- File headings with
``` 
@file
@brief

@author
@date
@copyright
```
as well as the MIT license. See existing files for an example.

- [ ]  <code>position.hpp</code>

- [ ]  <code>position.cpp</code>

- [ ]  <code>edge.hpp</code>

- [ ]  <code>edge.tpp</code>

- [ ]  <code>node.hpp</code>

- [ ]  <code>node.tpp</code>

- [ ]  <code>graph.tpp</code>
